### ISSUE TITLE
Codepage issue when reading pcon.json

### ISSUE THREAD

**Issue by PisuCat** [FracturedRetina/conlang-studio#1]
After selecting a directory, the tool crashes with this stack trace.

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
Caused by: org.json.JSONException: Duplicate key "Ê?" at 4054 [character 4055 line 1]
        at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
        at org.json.JSONObject.<init>(JSONObject.java:242)
        at org.json.JSONObject.<init>(JSONObject.java:399)
        at com.eshimoniak.conlangstudio.MarkdownExtensions.init(MarkdownExtensions.java:31)
        at com.eshimoniak.conlangstudio.Main.main(Main.java:41)
        ... 5 more
```

**Comment by rootmeanclaire** [comment]
Try the newest release, [v0.1.2](https://github.com/FracturedRetina/conlang-studio/releases/tag/v0.1.2)
